Make.delete_all
Make.create([{ name: 'Abarth', country: 'Italy' },
    { name: 'Acura', country: 'Japan' },
    { name: 'Alfa-Romeo', country: 'Italy' },
    { name: 'AMC', country: 'United States' },
    { name: 'Aston Martin', country: 'United Kingdom' },
    { name: 'Audi', country: 'Germany' },
    { name: 'Austin', country: 'United Kingdom' },
    { name: 'Austin-Healey', country: 'United Kingdom' },
    { name: 'Bentley', country: 'United Kingdom' },
    { name: 'BMW', country: 'Germany' },
    { name: 'Bufori', country: 'United Kingdom' },
    { name: 'Bugatti', country: 'France' },
    { name: 'Buick', country: 'United States' },
    { name: 'Cadillac', country: 'United States' },
    { name: 'Chana', country: 'China' },
    { name: 'Changfeng', country: 'China' },
    { name: 'Chery', country: 'China' },
    { name: 'Chevrolet', country: 'United States' },
    { name: 'Chrysler', country: 'United States' },
    { name: 'Citroën', country: 'France' },
    { name: 'Dacia', country: 'Romania' },
    { name: 'Daewoo', country: 'SouthKorea' },
    { name: 'Daihatsu', country: 'Japan' },
    { name: 'Dodge', country: 'United States' },
    { name: 'Dongfeng', country: 'China' },
    { name: 'Elfin', country: 'Australia' },
    { name: 'Ferrari', country: 'Italy' },
    { name: 'Fiat', country: 'Italy' },
    { name: 'Ford', country: 'United States' },
    { name: 'GM', country: 'United States' },
    { name: 'GMC', country: 'United States' },
    { name: 'GreatWall', country: 'China' },
    { name: 'Hafei', country: 'China' },
    { name: 'Haima', country: 'China' },
    { name: 'Holden', country: 'Australia' },
    { name: 'Honda', country: 'Japan' },
    { name: 'Hongqi', country: 'China' },
    { name: 'Hummer', country: 'United States' },
    { name: 'Hyundai', country: 'SouthKorea' },
    { name: 'Infiniti', country: 'Japan' },
    { name: 'Isuzu', country: 'Japan' },
    { name: 'Jaguar', country: 'United Kingdom' },
    { name: 'Jeep', country: 'United States' },
    { name: 'Kia', country: 'SouthKorea' },
    { name: 'Koenigsegg', country: 'Sweden' },
    { name: 'Lada (AvtoVAZ)', country: 'Russia' },
    { name: 'Lamborghini', country: 'Italy' },
    { name: 'Lancia', country: 'Italy' },
    { name: 'Land Rover', country: 'United Kingdom' },
    { name: 'Lexus', country: 'Japan' },
    { name: 'Leyland', country: 'United Kingdom' },
    { name: 'Lincoln', country: 'United States' },
    { name: 'Lotus', country: 'United Kingdom' },
    { name: 'Mahindra', country: 'India' },
    { name: 'Maserati', country: 'Italy' },
    { name: 'Maybach', country: 'Germany' },
    { name: 'Mazda', country: 'Japan' },
    { name: 'McLaren', country: 'United Kingdom' },
    { name: 'Mercedes-Benz', country: 'Germany' },
    { name: 'Mercury', country: 'United States' },
    { name: 'MG', country: 'United Kingdom' },
    { name: 'MINI', country: 'United Kingdom' },
    { name: 'Mitsubishi', country: 'Japan' },
    { name: 'Mitsuoka', country: 'Japan' },
    { name: 'Morgan', country: 'United Kingdom' },
    { name: 'Nissan', country: 'Japan' },
    { name: 'Oldsmobile', country: 'United States' },
    { name: 'Opel', country: 'Germany' },
    { name: 'Orion', country: 'Canada' },
    { name: 'Pagani', country: 'Italy' },
    { name: 'Perodua', country: 'Malaysia' },
    { name: 'Peugeot', country: 'France' },
    { name: 'Plymouth', country: 'United States' },
    { name: 'Pontiac', country: 'United States' },
    { name: 'Porsche', country: 'Germany' },
    { name: 'Proton', country: 'Malaysia' },
    { name: 'Ram', country: 'United States' },
    { name: 'Renault', country: 'France' },
    { name: 'Rolls-Royce', country: 'United Kingdom' },
    { name: 'Saab', country: 'Sweden' },
    { name: 'Saleen', country: 'United States' },
    { name: 'Saturn', country: 'United States' },
    { name: 'Scania', country: 'Sweden' },
    { name: 'Scion', country: 'United States' },
    { name: 'SEAT', country: 'Spain' },
    { name: 'Setra', country: 'Germany' },
    { name: 'Škoda', country: 'Czech Replublic' },
    { name: 'Smart', country: 'Germany' },
    { name: 'SsangYong', country: 'SouthKorea' },
    { name: 'Subaru', country: 'Japan' },
    { name: 'Suzuki', country: 'Japan' },
    { name: 'Tata', country: 'India' },
    { name: 'Tesla', country: 'United States' },
    { name: 'Toyota', country: 'Japan' },
    { name: 'Triumph', country: 'United Kingdom' },
    { name: 'TVR', country: 'United Kingdom' },
    { name: 'Vauxhall', country: 'United Kingdom' },
    { name: 'Volkswagen', country: 'Germany' },
    { name: 'Volvo', country: 'Sweden' },
    { name: 'Wuling', country: 'China' },
    { name: 'Zhongxing', country: 'China' } ])
